# Generated by Django 4.0.4 on 2022-04-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='products_or_product_a8a68e_idx',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['product', 'user'], name='products_or_product_895290_idx'),
        ),
    ]
