# Generated by Django 4.0.4 on 2022-04-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_order_options_alter_comment_date_posted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_created']},
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='products_co_product_ef361b_idx',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['product', 'user'], name='products_co_product_daed16_idx'),
        ),
    ]
