# Generated by Django 4.0.4 on 2022-04-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_comment_options_comment_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='deletion_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='not_spam',
            field=models.BooleanField(default=False),
        ),
    ]
